### ISSUE TITLE
Plugin org.apache.felix:maven-bundle-plugin:2.3.7 or one of its dependencies could not be resolved

### ISSUE THREAD

**Issue by pravins** [jgettext/gettext-commons#60]
I am trying to build this package on Fedora. Getting following error while build failure.

['xmvn', '--batch-mode', '--offline', '-Dmaven.test.skip=true', 'package', 'org.fedoraproject.xmvn:xmvn-mojo:install', 'org.apache.maven.plugins:maven-javadoc-plugin:aggregate', 'org.fedoraproject.xmvn:xmvn-mojo:builddep']
[INFO] Scanning for projects...
[WARNING] The POM for org.apache.felix:maven-bundle-plugin:jar:2.3.7 is missing, no dependency information available
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] The expression ${build.testOutputDirectory} is deprecated. Please use ${project.build.testOutputDirectory} instead. @ 
[WARNING] The expression ${pom.artifactId} is deprecated. Please use ${project.artifactId} instead. @ 
[ERROR] Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.3.7 or one of its dependencies could not be resolved: Cannot access central (https://repo.maven.apache.org/maven2) in offline mode and the artifact org.apache.felix:maven-bundle-plugin:jar:2.3.7 has not been downloaded from it before. @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.googlecode.gettext-commons:gettext-commons:0.9.9-SNAPSHOT (/NotBackedUp/git/gettext-commons/pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.3.7 or one of its dependencies could not be resolved: Cannot access central (https://repo.maven.apache.org/maven2) in offline mode and the artifact org.apache.felix:maven-bundle-plugin:jar:2.3.7 has not been downloaded from it before. -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1423598

**Comment by nicolas-f** [comment]
Hi,

Please check your internet connection (configure proxy in maven)

The missing dependency is available on maven central
 https://search.maven.org/#artifactdetails|org.apache.felix|maven-bundle-plugin|2.3.7|maven-plugin

**Comment by nicolas-f** [comment]
I see you have chosen offline mode. Disable it in order to download maven dependencies.
