### ISSUE TITLE
Maven plugin doesnt work

### ISSUE THREAD

**Issue by JuKu** [jgettext/gettext-commons#62]
Maven plugin doesnt generates any file.

```java
<plugin>
    <groupId>com.googlecode.gettext-commons</groupId>
    <artifactId>gettext-maven-plugin</artifactId>
    <version>1.2.4</version>
    <executions>
        <execution>
            <id>convert-po-class</id>
            <phase>compile</phase>
            <goals>
                <goal>dist</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <keysFile>messages.pot</keysFile>
        <poDirectory>${basedir}/../data/po</poDirectory>
        <targetBundle>com.jukusoft.rts.gui.GameGUI</targetBundle>
        <outputFormat>properties</outputFormat>
    </configuration>
</plugin>
```

**Comment by nicolas-f** [comment]
hi,
In order to update pot files, did you run ```mvn gettext:gettext``` on your project ?

**Comment by JuKu** [comment]
No, i didnt.
Do i have to? No .pot file exists yet, because no file was created.

**Comment by nicolas-f** [comment]
Yes. The translations procedure for projects is like this:

- some changes are done in the source code by developers
commit and push
- translation manager pull changes and run  `mvn gettext:gettext`  to create/update pot files from source code.
- translation manager commit and push pot files
- Changes of pot files are detected by web services like http://transifex.com and translators do the translations.
- translation manager pull transifex translations using the tx client tool.
- translation manager commit and push po files
- When running `mvn compile` po files are translated into java class file and included in the jar.

**Comment by JuKu** [comment]
Thanks for your answer!
This workflow is a little bit complicated.
Where can i found the translation manager?

**Comment by nicolas-f** [comment]
If you are working alone, just run `mvn gettext:gettext`, use a po editor for each language then run `mvn compile`

**Comment by JuKu** [comment]
Thanks!
